Feat: More fields to event and a geolaction model
HosterDu/Xenia pull request #10
Opened 2021-07-15 17:31 UTC by treyshotz

Just a suggestion...
I don't know where the best place to save the geolocation model is...

2021-07-15 20:13 UTC, Her0elt commented on backend/build.gradle.kts
> +        jvmTarget = "14"
Endre source complatebility også hvis du skal endre til java 14

2021-07-15 20:13 UTC, Her0elt commented on backend/src/main/kotlin/com/hosterdu/xenia/event/model/Event.kt
> +    val description: String,
Legg til at dette er et text felt slengden ikke er limited

2021-07-15 20:46 UTC, treyshotz commented on backend/src/main/kotlin/com/hosterdu/xenia/event/model/Event.kt
> +    val description: String,
wdym? annotation for databasen liksom?

2021-07-15 22:10 UTC, olros commented on backend/src/main/kotlin/com/hosterdu/xenia/event/model/Event.kt
> +    val description: String,
Db annotation ja, hvis ikke blir det maks sånn 200 tegn elns

2021-07-15 22:15 UTC, olros commented on backend/build.gradle.kts
> +java.sourceCompatibility = JavaVersion.VERSION_14
Hvorfor nedgradering til java 14 igjen?

2021-07-15 22:15 UTC, olros commented on backend/.idea/modules.xml
> +<project version="4">
Vi burde legge hele .idea mappen i .gitignore

2021-07-15 22:15 UTC, olros commented on backend/src/main/kotlin/com/hosterdu/xenia/event/model/Event.kt
> +    val image: String,
Finnes det en type/db annotasjon for url?

2021-07-16 15:09 UTC, Her0elt commented on backend/src/main/kotlin/com/hosterdu/xenia/event/model/Event.kt
> +    val description: String,
Ja sjekk rombestilling vi har det der på section

2021-07-16 15:13 UTC, Her0elt commented on backend/src/main/kotlin/com/hosterdu/xenia/event/model/Event.kt
> +    val image: String,
Ja tror det vinnes en @URL annotasjon

2021-07-16 16:02 UTC, treyshotz commented on backend/build.gradle.kts
> +java.sourceCompatibility = JavaVersion.VERSION_14
Jeg fikk build error når jeg prøvde å bruke 16....

2021-07-16 16:33 UTC, treyshotz commented on backend/.idea/modules.xml
> +<project version="4">
done

2021-07-16 16:33 UTC, treyshotz commented on backend/src/main/kotlin/com/hosterdu/xenia/event/model/Event.kt
> +    val image: String,
nei kunne ikke finne det ass....

2021-07-16 17:38 UTC, Zenjjim commented on backend/.idea/modules.xml
> +<project version="4">
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

Ifølge intellij skal ikke hele idea I gitignore. Sørger for at prosjektene har samme utgangspunkt

2021-07-16 17:38 UTC, Zenjjim commented on backend/build.gradle.kts
> +java.sourceCompatibility = JavaVersion.VERSION_14
Hva kommer denne erroren av? Har du husket å rebuilde gradle prosjektet?

2021-07-16 17:43 UTC, Zenjjim commented on backend/build.gradle.kts
> +java.sourceCompatibility = JavaVersion.VERSION_14
For dette kan komme av at du har bygd prosjektet for 14 før. Derfor du må rebuilde hele prosjektet for at det skal fungere

2021-07-16 17:44 UTC, Her0elt commented on backend/src/main/kotlin/com/hosterdu/xenia/event/model/Event.kt
> +    val image: String,
https://stackoverflow.com/questions/45969903/how-to-validate-website-url-field-of-an-jpa-entity test denne

2021-07-16 17:51 UTC, Zenjjim requested changes
Sykt bra jobba bro!!!

2021-07-16 17:51 UTC, Zenjjim commented on backend/src/main/kotlin/com/hosterdu/xenia/event/model/Event.kt
> +    val id: Long,
Jeg har en ide her. Er noe som heter [https://github.com/aventrix/jnanoid] (nanoid) og/eller [https://hashids.org/kotlin/](hashid) 

Jeg tenker vi kan bruke denne til å generere en fine Id enn som kan brukes I urlen og er lettere å dele 😊

2021-07-16 17:51 UTC, Zenjjim commented on backend/src/main/kotlin/com/hosterdu/xenia/event/model/Event.kt
> +    val endDate: ZonedDateTime,
Mulig å gjøre denne nullable

2021-07-16 17:51 UTC, Zenjjim commented on backend/src/main/kotlin/com/hosterdu/xenia/event/model/Event.kt
> +    val location: Geolocation,
Haha kult 🏖️

2021-07-16 17:51 UTC, Zenjjim commented on backend/.gitignore
> +.idea/
Nevnt I olaf sin kommentar 😊

2021-07-16 17:52 UTC, Zenjjim commented on backend/src/main/kotlin/com/hosterdu/xenia/event/model/Event.kt
> +    val location: Geolocation,
Hvordan vil dette gjøre tenker du. Via Google location api?

2021-08-06 15:01 UTC, closed without merging